export const USER_LOGOUT = 'user/USER_LOGOUT'
export const USER_SIGNIN = 'user/USER_SIGNIN'
export const GET_CURRENT_USER = 'user/GET_CURRENT_USER'
export const USER_SIGNIN_SUCCESS = 'user/USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'user/USER_SIGNIN_FAIL'
export const GET_BACKEND_DATA = 'user/GET_BACKEND_DATA'
